ho_ten=input("Nhap ho ten: ")
mssv=input("Nhap MSSV: ")
nganh=input("Nganh hoc: ")
nam_nhap_hoc=int(input("Nam nhap hoc"))
nam_tot_nghiep=nam_nhap_hoc + 3
print ("/n"+"="*45)
print("         THE SINH VIEN")
print("="*45)
print (f"Ho ten:  {ho_ten}")
print(f"  MSSV                : {mssv}")
print(f"  Nganh               : {nganh}")
print(f"  Nam nhap hoc        : {nam_nhap_hoc}")
print(f"  Nam tot nghiep  : {nam_tot_nghiep}")
print("=" * 45)
